Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804" # Cambiar si prefieres Ubuntu 20.04

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.boot_timeout = 600
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update && apt-get upgrade -y

    # Instalar dependencias necesarias
    apt-get install -y \
      wget \
      build-essential \
      autoconf \
      git \
      automake \
      libtool \
      libssl-dev \
      libcurl4-openssl-dev \
      libpcre3-dev \
      libspeexdsp-dev \
      libedit-dev \
      libopus-dev \
      libvpx-dev \
      libx264-dev \
      libxvidcore-dev \
      libjpeg-dev \
      libpng-dev \
      libtiff5-dev \
      libsndfile1-dev \
      libsqlite3-dev \
      libncurses5-dev \
      pkg-config \
      libxml2-dev

    # Descargar y compilar FreeSWITCH
    cd /usr/local/src
    git clone https://github.com/signalwire/freeswitch.git
    cd freeswitch
    ./bootstrap.sh
    ./configure
    make -j$(nproc) && make install

    # Instalar configuración de ejemplo y sonidos
    make samples
    make sounds-install

    # Configurar FreeSWITCH como servicio
    cp debian/freeswitch-systemd /etc/systemd/system/freeswitch.service
    systemctl daemon-reload
    systemctl enable freeswitch
    systemctl start freeswitch
  SHELL
end
